### PR TITLE
chore: update for renamed fields in Subarray

### PR DESCRIPTION
**Pull request by david-christiansen**

### CODE REVIEW

**Comment by david-christiansen** [comment]
Adaptation for https://github.com/leanprover/lean4/pull/3851 and https://github.com/leanprover/std4/pull/733

**Comment by david-christiansen** [comment]
@JLimperg I'm not entirely sure what the failing test for lists is testing - can you see if it is the test or the implementation that needs to be updated?

**Comment by JLimperg** [comment]
I've fixed some of the tests. The others are fixed in #117; please merge these.

**Comment by david-christiansen** [comment]
It looks like this was superseded by #123 - thanks for the help!

**Comment by kmill** [comment]
Sorry, I should have looked at the open PRs! I'd made the fix locally when getting mathlib back up to date.

**Pull request closed without merging**
