### PR TITLE
chore: adaptations for leanprover/lean4#2714

### PR DESCRIPTION
**Pull request by semorrison**
This has already been merged in `nightly-testing`, but I would like an approval in time for the next Lean version release next week if possible.

### CODE REVIEW

**Comment by JLimperg** [comment]
What is this `nightly-testing` exactly? A staging branch for the next Lean release?

**Comment by JLimperg** [comment]
The actual change is obviously fine. One test seems to be broken (and std as well), but the breakage seems to be trivial and unrelated to this change.

**Comment by semorrison** [comment]
> What is this `nightly-testing` exactly? A staging branch for the next Lean release?

Sorry, yes, it's a branch of `aesop` that Mathlib's `nightly-testing` can depend on, and includes all patches for Lean PRs that have landed in nightlies but not yet joined a release that `aesop` will bump to.

**Comment by semorrison** [comment]
I don't really have a solution at present for working CI for these sort of PRs. :-(

**Comment by JLimperg** [comment]
Superseded by #83.

**Pull request closed without merging**
